# coding=UTF-8

__author__ = ['Zhouhao']

# 通知时间变动。
# 在分、时、天、周一、月、年的开始会发出此事件
# 以后 plugin 中要在这些时间干一件事就不需要监听 HEART_BEAT 了
# 参数：newTimePoints：[string]
# 可能会包含 minute, hour, day, week, month, year
EV_NEW_TIME = 'EV_NEW_TIME'

# 游戏相关事件
# EV_USER_LOGIN = 'EV_USER_LOGIN'
# EV_GAME_INIT = 'EV_GAME_INIT'
# EV_GET_DA_SHI_FEN = 'EV_GET_DA_SHI_FEN'
EV_RELOAD_CONFIG = 'EV_RELOAD_CONFIG'
EV_SERVER_HEART_BEAT = 'EV_SERVER_HEART_BEAT'

# 快速开始
EV_BEFORE_ROOM_QUICK_START = 'EV_BEFORE_ROOM_QUICK_START'

# 房间相关事件
EV_LEAVE_ROOM = 'EV_LEAVE_ROOM'
EV_ENTER_ROOM = 'EV_ENTER_ROOM'
EV_CHECK_ENTER_ROOM_CONDITION = "EV_CHECK_ENTER_ROOM_CONDITION"  # 进入房间时检查条件

# 牌桌相关事件
EV_AFTER_TABLE_CHILD_INIT = 'EV_AFTER_TABLE_CHILD_INIT'
EV_LEAVE_TABLE = 'EV_LEAVE_TABLE'
EV_BEFORE_TABLE_CLEAR_PLAYERS = 'EV_BEFORE_TABLE_CLEAR_PLAYERS'

# 玩家相关事件
EV_AFTER_SITDOWN = 'EV_AFTER_SITDOWN'
EV_PLAYER_GAME_FRAME_START = 'EV_PLAYER_GAME_FRAME_START'  # 单个玩家一局开始
EV_PLAYER_GAME_FRAME_END = 'EV_PLAYER_GAME_FRAME_END'  # 单个玩家一局结束

# 玩法相关事件
EV_TRANSIT_TO_STATE_START_GAME = 'EV_TRANSIT_TO_STATE_START_GAME'
EV_AFTER_POT_BALANCE = 'EV_AFTER_POT_BALANCE'
EV_TRANSIT_TO_STATE_FINAL = 'EV_TRANSIT_TO_STATE_FINAL'

# 消息相关事件
EV_GET_GAME_DATA = 'EV_GET_GAME_DATA'
EV_GET_PLAYER_INFO = 'EV_GET_PLAYER_INFO'
EV_SEND_TABLE_INFO = 'EV_SEND_TABLE_INFO'

# http相关事件
EV_HTTP_COMMON_REQUEST = 'EV_HTTP_COMMON_REQUEST'  # 请求json
EV_HTTP_COMMON_REQUEST_PAGE = 'EV_HTTP_COMMON_REQUEST_PAGE'  # 请求动态页面

'''
EV_SEND_TABLE_READY = 'EV_SEND_TABLE_READY'
EV_TABLE_PREPARE_READY = 'EV_TABLE_PREPARE_READY'
EV_AFTER_HOLE_CARDS = 'EV_AFTER_HOLE_CARDS'
EV_USER_FOLD = 'EV_USER_FOLD'
EV_USER_CHECK = 'EV_USER_CHECK'
EV_USER_CALL = 'EV_USER_CALL'
EV_USER_RAISE = 'EV_USER_RAISE'
EV_USER_ALLIN = 'EV_USER_ALLIN'
EV_USER_EXCHAGE_CARDS = 'EV_USER_EXCHAGE_CARDS'

EV_POT_BALANCE = 'EV_POT_BALANCE'


EV_USER_DATA_UPDATE = 'EV_USER_DATA_UPDATE'
EV_START_PLAYER_PLAY_COUNTER = 'EV_START_PLAYER_PLAY_COUNTER'
EV_STOP_PLAYER_PLAY_COUNTER = 'EV_STOP_PLAYER_PLAY_COUNTER'
EV_AFTER_FLOP_CARDS = 'EV_AFTER_FLOP_CARDS'
EV_AFTER_TURN_CARDS = 'EV_AFTER_TURN_CARDS'
EV_AFTER_RIVER_CARDS = 'EV_AFTER_RIVER_CARDS'


EV_SEND_ANNOUNCE_LIST = 'EV_SEND_ANNOUNCE_LIST'
EV_SEND_GAME_CONFIG = 'EV_SEND_GAME_CONFIG'
EV_TABLE_CHAT = 'EV_TABLE_CHAT'
EV_TABLE_GM = 'EV_TABLE_GM' #牌桌管理
EV_USER_FIRST_SIT = 'EV_USER_FIRST_SIT'
EV_TEXAS_ACHIEVEMENT_COMPLETED = 'EV_TEXAS_ACHIEVEMENT_COMPLETED'
EV_GAME_SHOW_DOWN = 'EV_GAME_SHOW_DOWN'

EV_AFTER_BLIND_BET = 'EV_AFTER_BLIND_BET'
EV_AFTER_PRE_BET = 'EV_AFTER_PRE_BET'
EV_GAME_MERGEPOOL = 'EV_GAME_MERGEPOOL'


EV_AFTER_SEND_SHOW_DOWN_MSG = 'EV_AFTER_SEND_SHOW_DOWN_MSG'
EV_SEND_GAME_WIN_MSG_TO_PLAYER = 'EV_SEND_GAME_WIN_MSG_TO_PLAYER'
EV_PLAYER_ADD_WIN_CHIP = 'EV_PLAYER_ADD_WIN_CHIP'  # 给赢的玩家加钱
EV_START_NEXT_GAME = 'EV_START_NEXT_GAME'



#比赛事件
EV_MATCH_SIGN_UP = 'EV_MATCH_SIGN_UP'
EV_MATCH_SIGN_OUT = 'EV_MATCH_SIGN_OUT'
EV_MATCH_START = 'EV_MATCH_START'
EV_MATCH_END = 'EV_MATCH_END'
EV_USER_DELAY_ENTER_MATCH = 'EV_USER_DELAY_ENTER_MATCH'
EV_USER_MATCH_END = 'EV_USER_MATCH_END'
EV_BEFORE_MTT_REWARD_USER = 'EV_BEFORE_MTT_REWARD_USER'
EV_MTT_REWARD_USER = 'EV_MTT_REWARD_USER'

EV_PLAYER_SEE_CARD = 'EV_PLAYER_SEE_CARD'  # 看牌
EV_PLAYER_CHANGE_TABLE = 'EV_PLAYER_CHANGE_TABLE'  # 换桌
EV_PLAYER_SHOW_HOLE_CARD = 'EV_PLAYER_SHOW_HOLE_CARD'  # 亮手牌
EV_PLAYER_PK_CARD = 'EV_PLAYER_PK_CARD'  # 比牌

EV_ORDER_DELIVERY = 'EV_ORDER_DELIVERY'  # 购买后发货
EV_CHARGE_NOTIF = 'EV_CHARGE_NOTIF'  # 充值通知
EV_GAME_SEND_PLAYER_BETS_MSG = 'EV_GAME_SEND_PLAYER_BETS_MSG'
EV_GET_VIP_TABLE_LIST = 'EV_GET_VIP_TABLE_LIST'
EV_GET_VIP_TABLE_LIST_ITEM = 'EV_GET_VIP_TABLE_LIST_ITEM'
EV_AFTER_PLAYER_BET = 'EV_AFTER_PLAYER_BET'


EV_TABLE_GAMES = 'EV_TABLE_GAMES'



EV_FLIP_CARD_GAME = 'EV_FLIP_CARD_GAME'     # 翻了一把翻翻乐

EV_RED_ENVELOPE_GET_TODOTASK = 'EV_RED_ENVELOPE_GET_TODOTASK'
EV_RED_ENVELOPE_SHARE_SUCCESS = 'EV_RED_ENVELOPE_SHARE_SUCCESS'

EV_GET_T3CARD_HOLE_CARDS = 'EV_GET_T3CARD_HOLE_CARDS' # 三张发牌





EV_NEW_LIVE_SHOW_TABLE = 'EV_NEW_LIVE_SHOW_TABLE'
EV_OBSERVE = 'EV_OBSERVE'  # 观战

# 检查是否所有成就已完成
EV_CHECK_ACHIEVEMENTS_DONE = "EV_CHECK_ACHIEVEMENTS_DONE"



# 检查是否可以开始下一局
EV_CHECK_START_GAME_CONDITION = "EV_CHECK_START_GAME_CONDITION"

# 桌子处理一局结束
EV_TABLE_AFTER_GAME_END = "EV_TABLE_AFTER_GAME_END"

# 打通关的玩家，一局结束后等级结算
EV_PLAYER_DTG_BALANCE = "EV_PLAYER_DTG_BALANCE"
'''
